version: "3"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"  
  backend:
    build: ./backend
    ports:
      - "8071:8071"
    volumes:
      - logs:/app/logs
      - ./backend:/app  
      - /app/node_modules
    depends_on:
      - mongodb  

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
       - backend
volumes:
  data:       
  logs: